package TextpressoDatabaseCategories;

# Package contains categories that should be displayed.
# (c) 2007 Hans-Michael Muller, Caltech, Pasadena.

require Exporter;
our @ISA = qw(Exporter);
our @EXPORT = qw(DB_CATEGORIES DB_CATEGORYCHILDREN);

use strict;
use constant DB_CATEGORIES => {
    'action' => 'action',
#    'allele (C. elegans)' => 'allele_celegans',
    'allele' => 'allele',
#    'anatomy (C. elegans)' => 'anatomy_celegans',
#    'anatomy (D. melanogaster)' => 'anatomy_dmelanogaster',
    'anatomy' => 'anatomy',
    'antioxidant activity (GO)' => 'antioxidant_activity',
    'association' => 'association',
    'auxiliary transport protein activity (GO)' => 'auxiliary_transport_protein_activity',
    'binding (GO)' => 'binding',
    'biological adhesion (GO)' => 'biological_adhesion',
    'biological process (GO)' => 'biological_process',
    'biological regulation (GO)' => 'biological_regulation',
    'catalytic activity (GO)' => 'catalytic_activity',
    'cell (GO)' => 'cell',
    'cell part (GO)' => 'cell_part',
    'cellular component (GO)' => 'cellular_component',
    'cellular process (GO)' => 'cellular_process',
    'chaperone regulator activity (GO)' => 'chaperone_regulator_activity',
    'characterization' => 'characterization',
    'chemoattracant activity (GO)' => 'chemoattractant_activity',
    'chemorepellant activity (GO)' => 'chemorepellant_activity',
    'clone' => 'clone',
    'comparison' => 'comparison',
    'consort' => 'consort',
    'descriptor' => 'descriptor',
    'developmental process (GO)' => 'developmental_process',
#    'developmental stage (D. melanogaster)' => 'developmental_stage_dmelanogaster',
    'developmental stage' => 'developmental_stage',
#    'disease (H. sapiens)' => 'disease_hsapiens',
    'disease' => 'disease',
    'drugs' => 'drugs',
    'effect' => 'effect',
    'energy transducer activity (GO)' => 'energy_transducer_activity',
    'entity feature' => 'entity_feature',
    'envelope (GO)' => 'envelope',
    'enzyme regulator activity (GO)' => 'enzyme_regulator_activity',
    'establishment of localization (GO)' => 'establishment_of_localization',
    'extracellular matrix (GO)' => 'extracellular_matrix',
    'extracellular matrix part (GO)' => 'extracellular_matrix_part',
    'extracellular region (GO)' => 'extracellular_region',
    'extracellular region part (GO)' => 'extracellular_region_part',   
#    'gene (C. elegans)' => 'gene_celegans',
#    'gene (D. melanogaster)' => 'gene_dmelanogaster',
#    'gene (H. sapiens)' => 'gene_hsapiens',
#    'gene (N. crassa)' => 'gene_ncrassa',
    'gene' => 'gene',
    'growth (GO)' => 'growth',
    'involvement' => 'involvement',
#    'life stages (C. elegans)' => 'life_stages_celegans',
    'life stages' => 'life_stages',
    'localization (GO)' => 'localization_GO',
    'localization (Textpresso)' => 'localization',
    'locomotion (GO)' => 'locomotion',
    'maintenance of localization (GO)' => 'maintenance_of_localization',
#    'membrane enclosed lumen (GO)' => 'membrane_enclosed_lumen',
    'metabolic process (GO)' => 'metabolic_process',
    'method' => 'method',
    'molecular function (GO)' => 'molecular_function',
    'motor activity (GO)' => 'motor_activity',
#    'multi-organism process (GO)' => 'multi_organism_process',
#    'multicellular organismal process (GO)' => 'multicellular_organismal_process',
    'mutants' => 'mutants',
    'nucleic acid' => 'nucleic_acid',
    'nutrient reservoir activity (GO)' => 'nutrient_reservoir_activity',
#    'organelle (GO)' => 'organelle',
#    'organelle part (GO)' => 'organelle_part',
    'organism' => 'organism',
    'pathway' => 'pathway',
#    'phenotype (C. elegans)' => 'phenotype_celegans',
    'phenotype' => 'phenotype',
    'pigmentation (GO)' => 'pigmentation',
    'protein complex (GO)' => 'protein_complex',
    'protein tag (GO)' => 'protein_tag',
    'purpose' => 'purpose',
    'regulation' => 'regulation',
#    'reporter gene (C. elegans)' => 'reporter_gene_celegans',
    'reporter gene' => 'reporter_gene',
    'reproduction (GO)' => 'reproduction',
    'reproductive process (GO)' => 'reproductive_process',
    'response to stimulus (GO)' => 'response_to_stimulus',
    'restriction enzyme' => 'restriction_enzyme',
    'rhythmic process (GO)' => 'rhythmic_process',
    'second messenger' => 'second_messenger',
    'sequence (SO)' => 'sequence',
    'sex' => 'sex',
    'signal transducer activity (GO)' => 'signal_transducer_activity',
    'spatial relation' => 'spatial_relation',
    'strain' => 'strain',
    'structural molecule activity (GO)' => 'structural_molecule_activity',
#    'synapse (GO)' => 'synapse',
#    'synapse part (GO)' => 'synapse_part',
    'time relation' => 'time_relation',
    'transcription regulator activity (GO)' => 'transcription_regulator_activity',
#    'transgene (C. elegans)' => 'transgene_celegans',
    'transgene' => 'transgene',
    'translation regulator activity (GO)' => 'translation_regulator_activity',
    'transporter activity (GO)' => 'transporter_activity',
#    'transposon (D. melanogaster)' => 'transposon_dmelanogaster',
    'transposon' => 'transposon',
    'triplet codon amino acid adapter activity (GO)' => 'triplet_codon_amino_acid_adaptor_activity',
    'vector' => 'vector',
    'viral reproduction (GO)' => 'viral_reproduction',
    'virion (GO)' => 'virion',
    'virion part (GO)' => 'virion_part'
    };
use constant DB_CATEGORYCHILDREN => {
    'allele' => ['allele (C. elegans)'],
    'biological process (GO)' => ['biological adhesion (GO)', 
				  'biological regulation (GO)',
				  'cellular process (GO)',
				  'developmental process (GO)',
				  'establishment of localization (GO)',
				  'growth (GO)',
				  'localization (GO)',
				  'locomotion (GO)',
				  'maintenance of localization (GO)',
				  'metabolic process (GO)',
				  'multicellular organismal process (GO)',
				  'multi-organism process (GO)',
				  'pigmentation (GO)',
				  'reproduction (GO)',
				  'reproductive process (GO)',
				  'response to stimulus (GO)',
				  'rhythmic process (GO)',
				  'viral reproduction (GO)'],
    'cellular component (GO)' => ['cell (GO)',
				  'cell part (GO)',
				  'envelope (GO)',
				  'extracellular matrix (GO)',
				  'extracellular matrix part (GO)',
				  'extracellular region (GO)',
				  'extracellular region part (GO)',
				  'membrane enclosed lumen (GO)',
				  'organelle (GO)',
				  'organelle part (GO)',
				  'protein complex (GO)',
				  'synapse (GO)',
				  'synapse part (GO)',
				  'virion (GO)',
				  'virion part (GO)'],
    'developmental stage' => ['developmental stage (D. melanogaster)'],
    'disease' => ['disease (H. sapiens)'],
    'gene' => ['gene (C. elegans)', 'gene (D. melanogaster)', 'gene (H. sapiens)', 'gene (N. crassa)'],
    'life stages' => ['life stages (C. elegans)'],
    'localization (Textpresso)' => ['localization (GO)'],
    'molecular function (GO)' => ['antioxidant activity (GO)',
				  'auxiliary transport protein activity (GO)',
				  'binding (GO)',
				  'catalytic activity (GO)',
				  'chaperone regulator activity (GO)',
				  'chemoattracant activity (GO)',
				  'chemorepellant activity (GO)',
				  'energy transducer activity (GO)',
				  'enzyme regulator activity (GO)',
				  'motor activity (GO)',
				  'nutrient reservoir activity (GO)',
				  'protein tag (GO)',
				  'signal transducer activity (GO)',
				  'structural molecule activity (GO)',
				  'transcription regulator activity (GO)',
				  'translation regulator activity (GO)',
				  'transporter activity (GO)',
				  'triplet codon amino acid adapter activity (GO)'],
    'phenotype' => ['phenotype (C. elegans)'],
    'reporter gene' => ['reporter gene (C. elegans)'],
    'transgene' => ['transgene (C. elegans)'],
    'transposon' => ['transposon (D. melanogaster)']
    };
1;
